"""proyecto_videojuegos

Revision ID: 4da8ca1ed115
Revises: 3ca45a7a3fba
Create Date: 2026-04-14 15:59:35.165971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4da8ca1ed115'
down_revision: Union[str, None] = '3ca45a7a3fba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
