"""Initial migration: Create tables for videogames ETL

Revision ID: 3975d3c84938
Revises: 
Create Date: 2026-03-08 20:55:16.305116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3975d3c84938'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videojuegos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('fecha_lanzamiento', sa.Date(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('metacritic', sa.Float(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videojuegos_nombre'), 'videojuegos', ['nombre'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videojuegos_nombre'), table_name='videojuegos')
    op.drop_table('videojuegos')
    # ### end Alembic commands ###
