"""Add new columns for regression features

Revision ID: 3ca45a7a3fba
Revises: 408dff25e258
Create Date: 2026-04-12 18:44:16.070385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ca45a7a3fba'
down_revision: Union[str, None] = '408dff25e258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videojuegos', sa.Column('ratings_count', sa.Integer(), nullable=True))
    op.add_column('videojuegos', sa.Column('added', sa.Integer(), nullable=True))
    op.add_column('videojuegos', sa.Column('playtime', sa.Integer(), nullable=True))
    op.add_column('videojuegos', sa.Column('rating_top', sa.Float(), nullable=True))
    op.add_column('videojuegos', sa.Column('platforms', sa.Text(), nullable=True))
    op.add_column('videojuegos', sa.Column('genres', sa.Text(), nullable=True))
    op.add_column('videojuegos', sa.Column('esrb_rating', sa.String(length=50), nullable=True))
    op.add_column('videojuegos', sa.Column('developers', sa.Text(), nullable=True))
    op.add_column('videojuegos', sa.Column('publishers', sa.Text(), nullable=True))
    op.add_column('videojuegos_top', sa.Column('ratings_count', sa.Integer(), nullable=True))
    op.add_column('videojuegos_top', sa.Column('added', sa.Integer(), nullable=True))
    op.add_column('videojuegos_top', sa.Column('playtime', sa.Integer(), nullable=True))
    op.add_column('videojuegos_top', sa.Column('rating_top', sa.Float(), nullable=True))
    op.add_column('videojuegos_top', sa.Column('platforms', sa.Text(), nullable=True))
    op.add_column('videojuegos_top', sa.Column('genres', sa.Text(), nullable=True))
    op.add_column('videojuegos_top', sa.Column('esrb_rating', sa.String(length=50), nullable=True))
    op.add_column('videojuegos_top', sa.Column('developers', sa.Text(), nullable=True))
    op.add_column('videojuegos_top', sa.Column('publishers', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videojuegos_top', 'publishers')
    op.drop_column('videojuegos_top', 'developers')
    op.drop_column('videojuegos_top', 'esrb_rating')
    op.drop_column('videojuegos_top', 'genres')
    op.drop_column('videojuegos_top', 'platforms')
    op.drop_column('videojuegos_top', 'rating_top')
    op.drop_column('videojuegos_top', 'playtime')
    op.drop_column('videojuegos_top', 'added')
    op.drop_column('videojuegos_top', 'ratings_count')
    op.drop_column('videojuegos', 'publishers')
    op.drop_column('videojuegos', 'developers')
    op.drop_column('videojuegos', 'esrb_rating')
    op.drop_column('videojuegos', 'genres')
    op.drop_column('videojuegos', 'platforms')
    op.drop_column('videojuegos', 'rating_top')
    op.drop_column('videojuegos', 'playtime')
    op.drop_column('videojuegos', 'added')
    op.drop_column('videojuegos', 'ratings_count')
    # ### end Alembic commands ###
